force-app/main/default/objects/Account/fields/Court_Case__c.field-meta.xml
<CustomField>
    <fullName>Court_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Accounts related to Court Cases</description>
    <label>Court Case</label>
    <referenceTo>Court_Case__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Case_Junction__c/Account_Case_Junction__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Court Case</description>
    <label>Account Case Junction</label>
    <nameField>
        <displayFormat>ACJ-{0000000}</displayFormat>
        <label>Account Case Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Case Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Case_Junction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Court Cases</relationshipLabel>
    <relationshipName>Account_Case_Junctions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Case_Junction__c/fields/Court_Case__c.field-meta.xml
<CustomField>
    <fullName>Court_Case__c</fullName>
    <label>Court Case</label>
    <referenceTo>Court_Case__c</referenceTo>
    <relationshipLabel>Accounts Involved</relationshipLabel>
    <relationshipName>Account_Case_Junctions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Court_Case__c/Court_Case__c.object-meta.xml
<CustomObject>
    <description>Used to keep track of clients&#39; cases.</description>
    <label>Court Case</label>
    <nameField>
        <displayFormat>CC_{0000000}</displayFormat>
        <label>Court Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Court Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Witnesses.cls
public with sharing class Witnesses {
    
	@AuraEnabled(cacheable=false)
	public static List<WrapperClass> getHierarchy(Id curCase){
		System.debug('Getting object hierarchy');
		
		List<WrapperClass> wcList = new List<WrapperClass> ();

		List<Account_Case_Junction__c> junctionObjects = [SELECT Id, Account__c FROM Account_Case_Junction__c WHERE Court_Case__c = :curCase];
		List<Id> accountIdsToGrab = new List<Id> ();
		for (Account_Case_Junction__c acj : junctionObjects) {
			accountIdsToGrab.add(acj.Account__c);
		}
		List<Account> accountList = [SELECT Id, Name, Phone, (SELECT Id, Name, Phone FROM Contacts) FROM Account WHERE Id IN :accountIdsToGrab];

		for (Account a : accountList) {
			WrapperClass wc = new WrapperClass();
			wc.label = a.Name;
			wc.name = a.Name;
			wc.href = '/' +a.Id;
			wc.metatext = a.Phone;
			wc.expanded = true;
			List<Item> iList = new List<Item> ();
			for (Contact c : a.Contacts) {
				Item i = new Item();
				i.label = c.Name;
				i.name = c.Name;
				i.href = '/' +c.Id;
				i.metatext = c.Phone;
				iList.add(i);
			}
			wc.items = iList;
			wcList.add(wc);
		}

		System.debug(wcList);
		return wcList;
	}

	public class WrapperClass {
		@AuraEnabled
		public String label { get; set; }
		
		@AuraEnabled
		public String name { get; set; }

		@AuraEnabled
		public String href { get; set; }

		@AuraEnabled
		public String metatext { get; set; }

		@AuraEnabled
		public Boolean expanded { get; set; }              

		@AuraEnabled
		public List<Item> items { get; set; }
	}

	public class Item {
		@AuraEnabled
		public String label { get; set; }
		
		@AuraEnabled
		public String name { get; set; }

		@AuraEnabled
		public String href { get; set; }

		@AuraEnabled
		public String metatext { get; set; }

		@AuraEnabled
		public Boolean expanded { get; set; }
	}
}