force-app/main/default/objects/Account/fields/Court_Case__c.field-meta.xml
<CustomField>
    <fullName>Court_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Accounts related to Court Cases</description>
    <label>Court Case</label>
    <referenceTo>Court_Case__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Case_Junction__c/Account_Case_Junction__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Court Case</description>
    <label>Account Case Junction</label>
    <nameField>
        <displayFormat>ACJ-{0000000}</displayFormat>
        <label>Account Case Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Case Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Case_Junction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Court Cases</relationshipLabel>
    <relationshipName>Account_Case_Junctions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Case_Junction__c/fields/Court_Case__c.field-meta.xml
<CustomField>
    <fullName>Court_Case__c</fullName>
    <label>Court Case</label>
    <referenceTo>Court_Case__c</referenceTo>
    <relationshipLabel>Accounts Involved</relationshipLabel>
    <relationshipName>Account_Case_Junctions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Court_Case__c/Court_Case__c.object-meta.xml
<CustomObject>
    <description>Used to keep track of clients&#39; cases.</description>
    <label>Court Case</label>
    <nameField>
        <displayFormat>CC_{0000000}</displayFormat>
        <label>Court Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Court Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Court_Case__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Who we are representing in the case</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Court Cases as a Client</relationshipLabel>
    <relationshipName>Court_Cases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_Witnesses.cls
@isTest
private class Test_Witnesses {
    @TestSetup
	static void makeData(){
		Account clientAccount = new Account();
		clientAccount.Name = 'Test Client Account';
		clientAccount.Phone = '123-456-7890';

		Account witnessAccount = new Account();
		witnessAccount.Name = 'Test Witness Account';
		witnessAccount.Phone = '123-456-7890';
		
		List<Account> accountsToInsert = new List<Account>();
		accountsToInsert.add(clientAccount);
		accountsToInsert.add(witnessAccount);
		insert accountsToInsert;

		Contact clientContact = new Contact();
		clientContact.LastName = 'TestClient';
		clientContact.Phone = '098-765-4321';

		Contact witnessContact = new Contact();
		witnessContact.LastName = 'TestWitness';
		witnessContact.phone = '555-666-7777';
		witnessContact.accountId = witnessAccount.Id;

		List<Contact> contactsToInsert = new List<Contact>();
		contactsToInsert.add(clientContact);
		contactsToInsert.add(witnessContact);
		insert contactsToInsert;

		Court_Case__c cc = new Court_Case__c();
		cc.Client__c = clientAccount.Id;
		insert cc;
		
		Account_Case_Junction__c acj = new Account_Case_Junction__c();
		acj.Account__c = witnessAccount.Id;
		acj.Court_Case__c = cc.Id;
		insert acj;
	}

	@isTest
	static void testDataUpdate() {
		Contact c = [SELECT Id, Phone FROM Contact WHERE LastName = 'TestWitness' LIMIT 1];
		c.Phone = '555-666-7778';
		update c;

		Account a = [SELECT Id, Phone FROM Account WHERE Name = 'Test Client Account' LIMIT 1];
		a.Phone = '098-765-4322';
		update a;
	}

	@isTest
	static void testGetHierarchy() {
		List<Witnesses.WrapperClass> wc = Witnesses.getHierarchy([SELECT Id FROM Court_Case__c LIMIT 1].Id);
		System.assertEquals(1, wc.size());	//There is only 1 witness account, so only one should return
	}
}